### ISSUE TITLE
Some text is nearly unreadable

### ISSUE THREAD

**Issue by ghost** [catppuccin/qt5ct#1]
Certain dialogs (unfocused windows/subwindows, all VirtualBox text) lose all their contrast after applying the theme. I'm not sure what causes this, but it makes a several applications very hard to use.

**Comment by Syndrizzle** [comment]
Can you provide a screenshot?

**Comment by abrendtro** [comment]
Screenshots:

+ ![VirtualBox](https://user-images.githubusercontent.com/122829274/227741183-483f6be6-b065-4d54-9937-c1b4ba879aee.png)
![qt5](https://user-images.githubusercontent.com/122829274/227741269-fbd775b4-c1c6-4757-933d-e6ca9de1738b.png)

**Comment by abrendtro** [comment]
This is running in a GNOME environment, so QT support may be iffy

**Comment by abhishekmj303** [comment]
Facing same problem.. The text of the focused element is unreadable. When I hover over it, it makes it barely readable.

**Comment by dbt0815** [comment]
i might be a bit late, but i stumpled over this here and you are aware of the fact, that you can change the color palette in qt5c conf?

**Comment by shadow-absorber** [comment]
> i might be a bit late, but i stumpled over this here and you are aware of the fact, that you can change the color palette in qt5c conf?

yes but knowing what to change it to to still keep the catppuccin theming consistent is not that easy for a lot of people
